title: "LeafPulse"
description: "Exploring Eco-Friendly Technologies for Sustainable Living"
baseurl: "/leafpulse" # Leave empty for GitHub Pages root
url: "https://vantreltools.github.io" # Replace with your GitHub username
defaults:
  - scope:
      path: ""
    values:
      title: "LeafPulse | Eco-Friendly Tech for Sustainable Living"
      description: "Discover the latest eco-friendly technologies to live sustainably."